export const members = [
  {
    id: "1",
    name: "Patrick Harris",
    handle: "@christian",
    email: "p.harris@google.com",
    avatarUrl: "https://bit.ly/code-beast",
    status: "lead",
    workingHours: "yes",
    role: "VP of Engineering",
    rating: 4,
    localtime: "3:09:21 PM GMT+10",
  },
  {
    id: "2",
    name: "Kent Dodds",
    handle: "@kent",
    email: "kent@google.com",
    avatarUrl: "https://bit.ly/kent-c-dodds",
    status: "support",
    workingHours: "yes",
    role: "Director of Engineering",
    rating: 4,
    localtime: "US-East 11:43am",
  },
  {
    id: "3",
    name: "Prosper Otemuyiwa",
    handle: "@prosper",
    email: "prosper@google.com",
    avatarUrl: "https://bit.ly/prosper-baba",
    status: "support",
    workingHours: "no",
    role: "Senior Infra Engineer",
    rating: 4,
    localtime: "Singapore 10:43pm",
  },
  {
    id: "4",
    name: "Mark Jacobs",
    handle: "@ryan",
    email: "mark@google.com",
    avatarUrl: "https://bit.ly/ryan-florence",
    status: "support",
    workingHours: "yes",
    role: "Data Engineer",
    rating: 4,
    localtime: "London 2:43pm",
  },
  {
    id: "5",
    name: "Peter Adebayo",
    handle: "@segun",
    email: "peter@microsoft.com",
    avatarUrl: "https://bit.ly/sage-adebayo",
    status: "support",
    workingHours: "yes",
    role: "Frontend UI Engineer",
    rating: 4,
    localtime: "US-West 8:43am",
  },
];
