const data = {
  id: "6LTQgiWSqFCEzOYKY46LKg_0000",
  full_name: "viviana faga",
  first_name: "viviana",
  middle_initial: "p",
  middle_name: "padilla",
  last_initial: "f",
  last_name: "faga",
  gender: "female",
  birth_year: null,
  birth_date: null,
  linkedin_url: "linkedin.com/in/vivianafaga",
  linkedin_username: "vivianafaga",
  linkedin_id: "1265535",
  facebook_url: "facebook.com/vivpadilla",
  facebook_username: "vivpadilla",
  facebook_id: "620055889",
  twitter_url: "twitter.com/vivfaga",
  twitter_username: "vivfaga",
  github_url: null,
  github_username: null,
  work_email: "viviana@felicis.com",
  personal_emails: ["vivfaga@gmail.com"],
  recommended_personal_email: "vivfaga@gmail.com",
  mobile_phone: "+14153073647",
  industry: "venture capital & private equity",
  job_title: "general partner",
  job_title_role: null,
  job_title_sub_role: null,
  job_title_levels: ["partner"],
  job_company_id: "felicis-ventures",
  job_company_name: "felicis ventures",
  job_company_website: "felicis.com",
  job_company_size: "11-50",
  job_company_founded: 2006,
  job_company_industry: "venture capital & private equity",
  job_company_linkedin_url: "linkedin.com/company/felicis-ventures",
  job_company_linkedin_id: "209073",
  job_company_facebook_url: null,
  job_company_twitter_url: "twitter.com/felicisventures",
  job_company_location_name: "menlo park, california, united states",
  job_company_location_locality: "menlo park",
  job_company_location_metro: "san francisco, california",
  job_company_location_region: "california",
  job_company_location_geo: "37.45,-122.18",
  job_company_location_street_address: "2460 sand hill road",
  job_company_location_address_line_2: "suite 100",
  job_company_location_postal_code: "94025",
  job_company_location_country: "united states",
  job_company_location_continent: "north america",
  job_last_updated: "2023-05-12",
  job_start_date: "2021-09",
  location_name: "san francisco, california, united states",
  location_locality: "san francisco",
  location_metro: "san francisco, california",
  location_region: "california",
  location_country: "united states",
  location_continent: "north america",
  location_street_address: null,
  location_address_line_2: null,
  location_postal_code: null,
  location_geo: "37.77,-122.41",
  location_last_updated: "2023-02-27",
  phone_numbers: ["+14153073647"],
  emails: [
    { address: "viviana@emcap.com", type: "professional" },
    { address: "vivfaga@gmail.com", type: "personal" },
    { address: "viviana.faga@platfora.com", type: "professional" },
    { address: "vfaga@emcap.com", type: "professional" },
    { address: "viviana@felicis.com", type: "current_professional" },
  ],
  interests: [],
  skills: [
    "saas",
    "salesforce.com",
    "product marketing",
    "enterprise software",
    "cloud computing",
    "go to market strategy",
    "product management",
    "marketing",
    "sales enablement",
    "marketing strategy",
    "strategy",
    "start ups",
    "crm",
    "demand generation",
    "messaging",
    "cross functional team leadership",
    "online marketing",
    "social marketing",
    "product strategy",
    "software industry",
    "web analytics",
    "crm software",
    "positioning",
    "complex sales",
    "cloud applications",
    "social",
  ],
  location_names: ["san francisco, california, united states"],
  regions: ["california, united states"],
  countries: ["united states"],
  street_addresses: [],
  experience: [
    {
      company: {
        name: "walnut",
        size: "11-50",
        id: "teamwalnut",
        founded: 2020,
        industry: "computer software",
        location: {
          name: "new york, united states",
          locality: null,
          region: "new york",
          metro: null,
          country: "united states",
          continent: "north america",
          street_address: null,
          address_line_2: null,
          postal_code: null,
          geo: null,
        },
        linkedin_url: "linkedin.com/company/teamwalnut",
        linkedin_id: "67760135",
        facebook_url: "facebook.com/walnutai",
        twitter_url: "twitter.com/walnutinc",
        website: "walnut.io",
      },
      start_date: "2022-01",
      end_date: null,
      title: {
        name: "investor and board member",
        role: "finance",
        sub_role: "investment",
        levels: ["partner"],
      },
      location_names: [],
      is_primary: false,
    },
    {
      company: {
        name: "preql",
        size: "1-10",
        id: "preqldata",
        founded: null,
        industry: null,
        location: null,
        linkedin_url: "linkedin.com/company/preqldata",
        linkedin_id: "80559107",
        facebook_url: null,
        twitter_url: null,
        website: "preql.com",
      },
      start_date: "2022-05",
      end_date: null,
      title: {
        name: "investor",
        role: "finance",
        sub_role: "investment",
        levels: [],
      },
      location_names: [],
      is_primary: false,
    },
    {
      company: {
        name: "green places",
        size: "1-10",
        id: "green-places-to-work",
        founded: 2021,
        industry: "environmental services",
        location: {
          name: "raleigh, north carolina, united states",
          locality: "raleigh",
          region: "north carolina",
          metro: "raleigh, north carolina",
          country: "united states",
          continent: "north america",
          street_address: null,
          address_line_2: null,
          postal_code: "27604",
          geo: "35.76,-78.64",
        },
        linkedin_url: "linkedin.com/company/green-places-to-work",
        linkedin_id: "72677516",
        facebook_url: null,
        twitter_url: null,
        website: "greenplaces.com",
      },
      start_date: "2022-06",
      end_date: null,
      title: {
        name: "investor",
        role: "finance",
        sub_role: "investment",
        levels: [],
      },
      location_names: [],
      is_primary: false,
    },
    {
      company: {
        name: "meilisearch",
        size: "1-10",
        id: "meilisearch",
        founded: null,
        industry: "computer software",
        location: {
          name: "paris, ile-de-france, france",
          locality: "paris",
          region: "ile-de-france",
          metro: null,
          country: "france",
          continent: "europe",
          street_address: null,
          address_line_2: null,
          postal_code: null,
          geo: "48.86,2.33",
        },
        linkedin_url: "linkedin.com/company/meilisearch",
        linkedin_id: "13016868",
        facebook_url: null,
        twitter_url: null,
        website: "meilisearch.com",
      },
      location_names: ["paris, ile-de-france, france"],
      end_date: null,
      start_date: "2022-10",
      title: {
        name: "investor and board member",
        role: "finance",
        sub_role: "investment",
        levels: ["partner"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "runway",
        size: "1-10",
        id: "runwayml",
        founded: 2018,
        industry: "computer software",
        location: {
          name: "new york, united states",
          locality: null,
          region: "new york",
          metro: null,
          country: "united states",
          continent: "north america",
          street_address: null,
          address_line_2: null,
          postal_code: null,
          geo: null,
        },
        linkedin_url: "linkedin.com/company/runwayml",
        linkedin_id: "11741116",
        facebook_url: "facebook.com/runwayml",
        twitter_url: "twitter.com/runwayml",
        website: "runwayml.com",
      },
      location_names: [],
      end_date: null,
      start_date: "2022-12",
      title: {
        name: "investor and board observer",
        role: "finance",
        sub_role: "investment",
        levels: [],
      },
      is_primary: false,
    },
    {
      company: {
        name: "supabase",
        size: "1-10",
        id: "supabase",
        founded: null,
        industry: "information technology and services",
        location: null,
        linkedin_url: "linkedin.com/company/supabase",
        linkedin_id: "31546644",
        facebook_url: null,
        twitter_url: "twitter.com/supabase_io",
        website: "supabase.io",
      },
      location_names: [],
      end_date: null,
      start_date: "2022-05",
      title: {
        name: "investor and board observer",
        role: "finance",
        sub_role: "investment",
        levels: [],
      },
      is_primary: false,
    },
    {
      company: {
        name: "accenture",
        size: "10001+",
        id: "accenture",
        founded: 1989,
        industry: "information technology and services",
        location: {
          name: "dublin, dublin, ireland",
          locality: "dublin",
          region: "dublin",
          metro: null,
          country: "ireland",
          continent: "europe",
          street_address: null,
          address_line_2: null,
          postal_code: null,
          geo: "53.33,-6.24",
        },
        linkedin_url: "linkedin.com/company/accenture",
        linkedin_id: "1033",
        facebook_url: "facebook.com/accenture",
        twitter_url: "twitter.com/accenture",
        website: "accenture.com",
      },
      location_names: [],
      end_date: "2004",
      start_date: "2001",
      title: { name: "consultant", role: null, sub_role: null, levels: [] },
      is_primary: false,
    },
    {
      company: {
        name: "salesforce",
        size: "10001+",
        id: "salesforce",
        founded: 1999,
        industry: "internet",
        location: {
          name: "san francisco, california, united states",
          locality: "san francisco",
          region: "california",
          metro: "san francisco, california",
          country: "united states",
          continent: "north america",
          street_address: "1 market",
          address_line_2: null,
          postal_code: "94105",
          geo: "37.77,-122.41",
        },
        linkedin_url: "linkedin.com/company/salesforce",
        linkedin_id: "3185",
        facebook_url: "facebook.com/salesforce",
        twitter_url: "twitter.com/salesforce",
        website: "salesforce.com",
      },
      location_names: [],
      end_date: "2010-09",
      start_date: "2008-03",
      title: {
        name: "senior manager, product marketing",
        role: "marketing",
        sub_role: "product_marketing",
        levels: ["manager", "senior"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "salesforce",
        size: "10001+",
        id: "salesforce",
        founded: 1999,
        industry: "internet",
        location: {
          name: "san francisco, california, united states",
          locality: "san francisco",
          region: "california",
          metro: "san francisco, california",
          country: "united states",
          continent: "north america",
          street_address: "1 market",
          address_line_2: null,
          postal_code: "94105",
          geo: "37.77,-122.41",
        },
        linkedin_url: "linkedin.com/company/salesforce",
        linkedin_id: "3185",
        facebook_url: "facebook.com/salesforce",
        twitter_url: "twitter.com/salesforce",
        website: "salesforce.com",
      },
      location_names: [],
      end_date: "2008-03",
      start_date: "2004-06",
      title: {
        name: "senior sales engineer, global enterprise accounts",
        role: "sales",
        sub_role: "accounts",
        levels: ["senior"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "felicis ventures",
        size: "11-50",
        id: "felicis-ventures",
        founded: 2006,
        industry: "venture capital & private equity",
        location: {
          name: "menlo park, california, united states",
          locality: "menlo park",
          region: "california",
          metro: "san francisco, california",
          country: "united states",
          continent: "north america",
          street_address: "2460 sand hill road",
          address_line_2: "suite 100",
          postal_code: "94025",
          geo: "37.45,-122.18",
        },
        linkedin_url: "linkedin.com/company/felicis-ventures",
        linkedin_id: "209073",
        facebook_url: null,
        twitter_url: "twitter.com/felicisventures",
        website: "felicis.com",
      },
      location_names: [],
      end_date: null,
      start_date: "2021-09",
      title: {
        name: "general partner",
        role: null,
        sub_role: null,
        levels: ["partner"],
      },
      is_primary: true,
    },
    {
      company: {
        name: "emergence capital",
        size: "11-50",
        id: "emergence-capital-partners",
        founded: 2004,
        industry: "venture capital & private equity",
        location: {
          name: "san mateo, california, united states",
          locality: "san mateo",
          region: "california",
          metro: "san francisco, california",
          country: "united states",
          continent: "north america",
          street_address: "160 bovet road",
          address_line_2: "suite 300",
          postal_code: "94402",
          geo: "37.56,-122.32",
        },
        linkedin_url: "linkedin.com/company/emergence-capital-partners",
        linkedin_id: "218022",
        facebook_url: "facebook.com/emergencecapitalpartners",
        twitter_url: "twitter.com/emergencecap",
        website: "emcap.com",
      },
      location_names: [],
      end_date: "2020-10",
      start_date: "2017-09",
      title: {
        name: "operating partner",
        role: "operations",
        sub_role: null,
        levels: ["partner"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "jive software",
        size: "501-1000",
        id: "jive-software",
        founded: 2001,
        industry: "computer software",
        location: {
          name: "campbell, california, united states",
          locality: "campbell",
          region: "california",
          metro: "san jose, california",
          country: "united states",
          continent: "north america",
          street_address: "300 orchard city drive",
          address_line_2: "suite 100",
          postal_code: "95008",
          geo: "37.28,-121.94",
        },
        linkedin_url: "linkedin.com/company/jive-software",
        linkedin_id: "19867",
        facebook_url: "facebook.com/fans.of.jive",
        twitter_url: "twitter.com/jivesoftware",
        website: "jivesoftware.com",
      },
      location_names: [],
      end_date: "2012",
      start_date: "2010",
      title: {
        name: "senior manager, product marketing",
        role: "marketing",
        sub_role: "product_marketing",
        levels: ["manager", "senior"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "microsoft",
        size: "10001+",
        id: "microsoft",
        founded: 1975,
        industry: "computer software",
        location: {
          name: "redmond, washington, united states",
          locality: "redmond",
          region: "washington",
          metro: "seattle, washington",
          country: "united states",
          continent: "north america",
          street_address: "1 microsoft way",
          address_line_2: null,
          postal_code: "98052",
          geo: "47.67,-122.12",
        },
        linkedin_url: "linkedin.com/company/microsoft",
        linkedin_id: "1035",
        facebook_url: "facebook.com/microsoft",
        twitter_url: "twitter.com/microsoft",
        website: "microsoft.com",
      },
      location_names: ["san francisco, california, united states"],
      end_date: "2014-02",
      start_date: "2013-02",
      title: {
        name: "head of enterprise social marketing",
        role: "marketing",
        sub_role: null,
        levels: ["director"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "platfora",
        size: "51-200",
        id: "platfora",
        founded: 2011,
        industry: "computer software",
        location: {
          name: "san mateo, california, united states",
          locality: "san mateo",
          region: "california",
          metro: "san francisco, california",
          country: "united states",
          continent: "north america",
          street_address: "1300 south el camino real",
          address_line_2: "floor 6th",
          postal_code: "94402",
          geo: "37.56,-122.32",
        },
        linkedin_url: "linkedin.com/company/platfora",
        linkedin_id: "2267380",
        facebook_url: "facebook.com/platfora",
        twitter_url: "twitter.com/platfora",
        website: "platfora.com",
      },
      location_names: [],
      end_date: "2016-05",
      start_date: "2014-04",
      title: {
        name: "vice president, marketing",
        role: "marketing",
        sub_role: null,
        levels: ["vp"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "yammer, inc.",
        size: "51-200",
        id: "yammer-inc",
        founded: 2008,
        industry: "computer software",
        location: {
          name: "san francisco, california, united states",
          locality: "san francisco",
          region: "california",
          metro: "san francisco, california",
          country: "united states",
          continent: "north america",
          street_address: "1355 market street",
          address_line_2: null,
          postal_code: "94103",
          geo: "37.77,-122.41",
        },
        linkedin_url: "linkedin.com/company/yammer-inc",
        linkedin_id: "260901",
        facebook_url: "facebook.com/jakeludington",
        twitter_url: "twitter.com/yammer",
        website: "yammer.com",
      },
      location_names: ["san francisco, california, united states"],
      end_date: "2014",
      start_date: "2013-02",
      title: {
        name: "vice president, marketing",
        role: "marketing",
        sub_role: null,
        levels: ["vp"],
      },
      is_primary: false,
    },
    {
      company: {
        name: "zenefits",
        size: "501-1000",
        id: "zenefits",
        founded: 2013,
        industry: "human resources",
        location: {
          name: "san francisco, california, united states",
          locality: "san francisco",
          region: "california",
          metro: "san francisco, california",
          country: "united states",
          continent: "north america",
          street_address: "50 beale street",
          address_line_2: null,
          postal_code: "94105",
          geo: "37.77,-122.41",
        },
        linkedin_url: "linkedin.com/company/zenefits",
        linkedin_id: "2997680",
        facebook_url: "facebook.com/zenefits",
        twitter_url: "twitter.com/zenefits",
        website: "zenefits.com",
      },
      location_names: ["san francisco, california, united states"],
      end_date: "2017",
      start_date: "2016",
      title: {
        name: "chief marketing officer",
        role: "marketing",
        sub_role: null,
        levels: ["cxo"],
      },
      is_primary: false,
    },
  ],
  education: [
    {
      school: {
        name: "santa clara university",
        type: "post-secondary institution",
        id: "5dKAX7iVblfAhgMn5t4OYQ_0",
        location: {
          name: "santa clara, california, united states",
          locality: "santa clara",
          region: "california",
          country: "united states",
          continent: "north america",
        },
        linkedin_url: "linkedin.com/school/santa-clara-university",
        facebook_url: "facebook.com/santaclarauniversity",
        twitter_url: "twitter.com/santaclarauniv",
        linkedin_id: "17914",
        website: "scu.edu",
        domain: "scu.edu",
      },
      degrees: ["bachelors", "bachelor of science"],
      start_date: null,
      end_date: null,
      majors: ["operations management", "information systems"],
      minors: [],
      gpa: null,
    },
  ],
  profiles: [
    {
      network: "linkedin",
      id: "1265535",
      url: "linkedin.com/in/vivianafaga",
      username: "vivianafaga",
    },
    {
      network: "facebook",
      id: "620055889",
      url: "facebook.com/vivpadilla",
      username: "vivpadilla",
    },
    {
      network: "twitter",
      id: null,
      url: "twitter.com/vivfaga",
      username: "vivfaga",
    },
    {
      network: "klout",
      id: null,
      url: "klout.com/vivfaga",
      username: "vivfaga",
    },
    {
      network: "vimeo",
      id: null,
      url: "vimeo.com/jivesalesforce",
      username: "jivesalesforce",
    },
    {
      network: "angellist",
      id: null,
      url: "angel.co/vivfaga",
      username: "vivfaga",
    },
    {
      network: "linkedin",
      id: null,
      url: "linkedin.com/in/viviana-faga-453510",
      username: "viviana-faga-453510",
    },
    {
      network: "youtube",
      id: null,
      url: "youtube.com/user/ucp-3zarewi8sgl3mpelzmkg",
      username: "ucp-3zarewi8sgl3mpelzmkg",
    },
  ],
  version_status: {
    status: "",
    contains: [],
    previous_version: "",
    current_version: "",
  },
};
