const data = {
  id: "6LTQgiWSqFCEzOYKY46LKg_0000",
  full_name: "viviana faga",
  first_name: "viviana",
  middle_initial: "p",
  middle_name: "padilla",
  last_initial: "f",
  last_name: "faga",
  gender: "female",
  birth_year: null,
  birth_date: null,
  linkedin_url: "linkedin.com/in/vivianafaga",
  linkedin_username: "vivianafaga",
  linkedin_id: "1265535",
  facebook_url: "facebook.com/vivpadilla",
  facebook_username: "vivpadilla",
  facebook_id: "620055889",
  twitter_url: "twitter.com/vivfaga",
  twitter_username: "vivfaga",
  github_url: null,
  github_username: null,
  work_email: "viviana@felicis.com",
  personal_emails: ["vivfaga@gmail.com"],
  recommended_personal_email: "vivfaga@gmail.com",
  mobile_phone: "+14153073647",
  industry: "venture capital & private equity",
  job_title: "general partner",
  job_title_role: null,
  job_title_sub_role: null,
  job_title_levels: ["partner"],
  job_company_id: "felicis-ventures",
  job_company_name: "felicis ventures",
  job_company_website: "felicis.com",
  job_company_size: "11-50",
  job_company_founded: 2006,
  job_company_industry: "venture capital & private equity",
  job_company_linkedin_url: "linkedin.com/company/felicis-ventures",
  job_company_linkedin_id: "209073",
  job_company_facebook_url: null,
  job_company_twitter_url: "twitter.com/felicisventures",
  job_company_location_name: "menlo park, california, united states",
  job_company_location_locality: "menlo park",
  job_company_location_metro: "san francisco, california",
  job_company_location_region: "california",
  job_company_location_geo: "37.45,-122.18",
  job_company_location_street_address: "2460 sand hill road",
  job_company_location_address_line_2: "suite 100",
  job_company_location_postal_code: "94025",
  job_company_location_country: "united states",
  job_company_location_continent: "north america",
  job_last_updated: "2023-03-24",
  job_start_date: "2021-09",
  location_name: "san francisco, california, united states",
  location_locality: "san francisco",
  location_metro: "san francisco, california",
  location_region: "california",
  location_country: "united states",
  location_continent: "north america",
  location_street_address: null,
  location_address_line_2: null,
  location_postal_code: null,
  location_geo: "37.77,-122.41",
  location_last_updated: "2023-02-27",
  phone_numbers: ["+14153073647"],
  emails: [
    { address: "viviana@emcap.com", type: "professional" },
    { address: "vivfaga@gmail.com", type: "personal" },
    { address: "viviana.faga@platfora.com", type: "professional" },
    { address: "vfaga@emcap.com", type: "professional" },
    { address: "viviana@felicis.com", type: "current_professional" },
  ],
  interests: [],
  skills: [
    "saas",
    "salesforce.com",
    "product marketing",
    "enterprise software",
    "cloud computing",
    "go to market strategy",
    "product management",
    "marketing",
    "sales enablement",
    "marketing strategy",
    "strategy",
    "start ups",
    "crm",
    "demand generation",
    "messaging",
    "cross functional team leadership",
    "online marketing",
    "social marketing",
    "product strategy",
    "software industry",
    "web analytics",
    "crm software",
    "positioning",
    "complex sales",
    "cloud applications",
    "social",
  ],
  location_names: ["san francisco, california, united states"],
  regions: ["california, united states"],
  countries: ["united states"],
  street_addresses: [],
  experience: [
    {
      company: {
        name: "walnut",
        size: "11-50",
        id: "teamwalnut",
        founded: 2020,
        industry: "computer software",
        location: {
          name: "new york, united states",
          locality: null,
          region: "new york",
          metro: null,
          country: "united states",
          continent: "north america",
          street_address: null,
          address_line_2: null,
          postal_code: null,
          geo: null,
        },
        linkedin_url: "linkedin.com/company/teamwalnut",
        linkedin_id: "67760135",
        facebook_url: "facebook.com/walnutai",
        twitter_url: "twitter.com/walnutinc",
        website: "walnut.io",
      },
      start_date: "2022-01",
      end_date: null,
      title: {
        name: "investor and board member",
        role: "finance",
        sub_role: "investment",
        levels: ["partner"],
      },
      location_names: [],
      is_primary: false,
    },
    {
      company: {
        name: "preql",
        size: "1-10",
        id: "preqldata",
        founded: null,
        industry: null,
        location: null,
        linkedin_url: "linkedin.com/company/preqldata",
        linkedin_id: "80559107",
        facebook_url: null,
        twitter_url: null,
        website: "preql.com",
      },
      start_date: "2022-05",
      end_date: null,
      title: {
        name: "investor",
        role: "finance",
        sub_role: "investment",
        levels: [],
      },
      location_names: [],
      is_primary: false,
    },
  ],
  education: [
    {
      school: {
        name: "santa clara university",
        type: "post-secondary institution",
        id: "5dKAX7iVblfAhgMn5t4OYQ_0",
        location: {
          name: "santa clara, california, united states",
          locality: "santa clara",
          region: "california",
          country: "united states",
          continent: "north america",
        },
        linkedin_url: "linkedin.com/school/santa-clara-university",
        facebook_url: "facebook.com/santaclarauniversity",
        twitter_url: "twitter.com/santaclarauniv",
        linkedin_id: "17914",
        website: "scu.edu",
        domain: "scu.edu",
      },
      degrees: ["bachelors", "bachelor of science"],
      start_date: null,
      end_date: null,
      majors: ["operations management", "information systems"],
      minors: [],
      gpa: null,
    },
  ],
  profiles: [
    {
      network: "linkedin",
      id: "1265535",
      url: "linkedin.com/in/vivianafaga",
      username: "vivianafaga",
    },
    {
      network: "facebook",
      id: "620055889",
      url: "facebook.com/vivpadilla",
      username: "vivpadilla",
    },
    {
      network: "twitter",
      id: null,
      url: "twitter.com/vivfaga",
      username: "vivfaga",
    },
    {
      network: "klout",
      id: null,
      url: "klout.com/vivfaga",
      username: "vivfaga",
    },
    {
      network: "vimeo",
      id: null,
      url: "vimeo.com/jivesalesforce",
      username: "jivesalesforce",
    },
    {
      network: "angellist",
      id: null,
      url: "angel.co/vivfaga",
      username: "vivfaga",
    },
    {
      network: "linkedin",
      id: null,
      url: "linkedin.com/in/viviana-faga-453510",
      username: "viviana-faga-453510",
    },
    {
      network: "youtube",
      id: null,
      url: "youtube.com/user/ucp-3zarewi8sgl3mpelzmkg",
      username: "ucp-3zarewi8sgl3mpelzmkg",
    },
  ],
  version_status: {
    status: "",
    contains: [],
    previous_version: "",
    current_version: "",
  },
};
